language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - ruby-head
  - jruby-head

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile

sudo: false

notifications:
  email:
    - agresso@gmail.com

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
